server:
  port: 9001    
#spring:     #定义springmvc视图解析器
  #mvc:
    #view:
      #prefix: /WEB-INF/
      #suffix: .html
spring:  resources:    static-locations: classpath:/templates/#引入dubbo的配置
#dubbo:
  #scan:
    #basePackages: com.jt
  #application:
    #name: consumer-web
  #registry:
    #address: zookeeper://192.168.44.4:2181?backup=192.168.44.4:2182,192.168.44.4:2183